title: teach-a-computer-to-read
hero_image: images/banner.png
description: teach-a-computer-to-read description
version: 4
listed: false
copyedit: false
last_tested: "2020-12-02"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
