title: Teach a computer to read
hero_image: images/banner.png
description: Build a machine vision model with TensorFlow to teach a computer to recognise handwritten numbers.
version: 4
listed: true
copyedit: true
last_tested: "2020-06-29"
steps:
  - title: Introduction
  - title: Get some training data
  - title: Explore and prepare your data
  - title: Build your model
  - title: Compile your model
  - title: Train your model
  - title: Test your model
  - title: What next?
